---
  - name: creating folder for cloning landing zone terraform code
    file:
      path: "{{role_path}}/files/terraform/{{lz_repo}}"
      state: directory


  - name: cloning landing zone terraform repositories
    git:
      dest: "{{role_path}}/files/terraform/{{lz_repo}}"
      repo: "{{git_url}}/{{git_org}}/{{lz_repo}}.git"


  - name: deploying landing zone
    terraform:
      project_path: "{{role_path}}/files/terraform/{{lz_repo}}"
      force_init: true
      init_reconfigure: true
      state: "{{state}}"
      variables:
          AWS_ACCESS_KEY: "{{aws_access_key}}"
          AWS_SECRET_KEY: "{{aws_secret_key}}"
          cust_id: "{{cust_id}}"

  - name: creating folder for cloning eks terraform code
    file:
      path: "{{role_path}}/files/terraform/{{eks_repo}}"
      state: directory

  - name: cloning eks terraform repositories
    git:
      dest: "{{role_path}}/files/terraform/{{eks_repo}}"
      repo: "{{git_url}}/{{git_org}}/{{eks_repo}}.git"

  - name: deploying eks cluster
    terraform:
      project_path: "{{role_path}}/files/terraform/{{eks_repo}}"
      init_reconfigure: true
      force_init: true
      state: "{{state}}"
      variables:
          AWS_ACCESS_KEY: "{{aws_access_key}}"
          AWS_SECRET_KEY: "{{aws_secret_key}}"
          cust_id: "{{cust_id}}"

  - name: setting iam role for eks service account
    ansible.builtin.shell:
      cmd: eksctl create iamserviceaccount   --cluster="{{cust_id}}-eks" --namespace=kube-system   --name=aws-load-balancer-controller   --role-name AmazonEKSLoadBalancerControllerRole   --attach-policy-arn=arn:aws:iam::{{aws_account}}:policy/AWSLoadBalancerControllerIAMPolicy --approve

  - name: creating folder for cloning argocd terraform code
    file:
      path: "{{role_path}}/files/terraform/{{argo_repo}}"
      state: directory

  - name: cloning argocd terraform repositories
    git:
      dest: "{{role_path}}/files/terraform/{{argo_repo}}"
      repo: "{{git_url}}/{{git_org}}/{{argo_repo}}.git"

  - name: deploying argocd
    terraform:
      project_path: "{{role_path}}/files/terraform/{{argo_repo}}"
      init_reconfigure: true
      force_init: true
      state: "{{state}}"
      variables:
          AWS_ACCESS_KEY: "{{aws_access_key}}"
          AWS_SECRET_KEY: "{{aws_secret_key}}"
          cust_id: "{{cust_id}}"

  - name: Creating ArgoCD project
    kubernetes.core.k8s:
      state: present
      src: "{{role_path}}/files/terraform/{{argo_repo}}/apps/project.yaml"

  - name: Create a mediawiki namespace
    kubernetes.core.k8s:
      name: mediawiki
      api_version: v1
      kind: Namespace
      state: present

  - name: Creating ArgoCD application
    kubernetes.core.k8s:
      state: present
      src: "{{role_path}}/files/terraform/{{argo_repo}}/apps/app.yaml"

## Destroy tasks start here

  - name: destroying argocd
    terraform:
      project_path: "{{role_path}}/files/terraform/{{argo_repo}}"
      init_reconfigure: true
      force_init: true
      state: "{{state}}"
      variables:
          AWS_ACCESS_KEY: "{{aws_access_key}}"
          AWS_SECRET_KEY: "{{aws_secret_key}}"
          cust_id: "{{cust_id}}"
    tags:
      - destroy
  - name: deleting folder for argocd terraform code
    file:
      path: "{{role_path}}/files/terraform/{{argo_repo}}"
      state: absent
    tags:
      - destroy


  - name: destroying eks cluster
      project_path: "{{role_path}}/files/terraform/{{eks_repo}}"
      init_reconfigure: true
      force_init: true
      state: "{{state}}"
      variables:
          AWS_ACCESS_KEY: "{{aws_access_key}}"
          AWS_SECRET_KEY: "{{aws_secret_key}}"
          cust_id: "{{cust_id}}"
    tags:
      - destroy
  - name: deleting folder for eks terraform code
    file:
      path: "{{role_path}}/files/terraform/{{eks_repo}}"
      state: absent
    tags:
      - destroy
  - name: destroying landing zone
    terraform:
      project_path: "{{role_path}}/files/terraform/{{lz_repo}}"
      force_init: true
      init_reconfigure: true
      state: "{{state}}"
      variables:
          AWS_ACCESS_KEY: "{{aws_access_key}}"
          AWS_SECRET_KEY: "{{aws_secret_key}}"
          cust_id: "{{cust_id}}"
    tags:
      - destroy
  - name: deleting folder for landing zone terraform code
    file:
      path: "{{role_path}}/files/terraform/{{lz_repo}}"
      state: absent
    tags:
      - destroy